- name: nginx install and run
  hosts: frontend
  become: yes #sudo access
  tasks:
  - name : install nginx server 
    ansible.builtin.package:
      name: nginx
      state: present # present means nginx is install and state = absent means nginx is uninstall
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes