- name: variables from prompt
  hosts: local
  connection: local
  tasks:
  vars_prompt:
  - name: USERNAME #hear USERNAME is variable
    prompt: please enter your usernmae
    private: true
  - name: PASSWORD # hear PASSWORD is variable
    prompt: please enter your password
    private: true
  tasks:
  - name: printing user information
    ansible.builtin.debug:
      msg: "hello usernmae is {{ USERNAME}}, password is {{ PASSWORD }}"
