- name: variables from inventory
  hosts: local
  connection: local
  tasks:
  - name: print the course information
    ansible.builtin.debug:
      msg: " hello course name is {{ COURSE }}, duration is {{ DURATION }}, trainer is {{ TRAINER }}"
