- name: ansible datatypes
  hosts: local
  connection: local
  vars:
    DURATION: 120 #THIS IS NUMBER
    COURSE: "DEVOPS" # this is string
    IS_LIVE: true # this is boolean
    tools: #list
    - linux
    - ansible
    - shell
    concepts: # objects, map{if line is start with - that is list otherwise map or onject..object is reffer {} braces}
      ci: jenkins
      scripting: "shell, ansible, terraform, python"
    tasks:
    - name: print course information
      ansible.builtin.debug:
        msg: "{{ COURSE }},{{ DURATION }}, {{IS_LIVE }}, tooles are: {{ tools }}"
