- name: playbook control using ansible facts
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx if redhat 
    ansible.builtin.dnf:
      name: nginx
      state: present
    when: ansible_os_family == "Redhat"
  - name: install nginx if dabian 
    ansible.builtin.apt:
      name: nginx
      state: present
    when: ansible_os_family == "dabian"