- name: loops
  hosts: local
  connection: local
  tasks:
  - name: print names
    ansible.builtin.debug:
       msg: "hello {{ item }}" #hear item is a reserved keyword
    loop:
    - suresh
    - ramesh
