- name: functions
  hosts: local
  connection: local
  vars:
    person: "ramesh,suresh,raheem,joseph"
  tasks: 
  - name: check undefined variable
    ansible.builtin.debug:
      msg: "hello {{ person | default('ramesh') }}"

  - name: print names
    ansible.builtin.debug:
       msg: "{{ person | split(',') }}"

  - name: convert map into list
    vars:
      course:
       name: devops
       duration: 120 hrs
       trainer: siva
    ansible.builtin.debug:
       msg: "course information: {{ course | dict2items }}"
  - name: convert list into map
    vars:
     course:
     - {'key': 'name', 'value': 'devops'}
     - {'key': 'duration', 'value': '10hr'}
     - {'key': 'trainer', 'value': 'siva'}
    ansible.builtin.debug:
      msg: "course information: {{ course | items2dict }}"
  - name: convert upper case to lower case
    vars:
      name: "surekha reddy bana"
    ansible.builtin.debug:
      msg: "{{ name | upper }}"

  - name: convert to lowercase
    vars:
      name: "surekhareddy BANA"
    ansible.builtin.debug:
      msg: "{{ name | lower }}"

  - name: check ip address valid or not
    vars:
       ip: "300.567.980.789"
    ansible.builtin.debug:
      msg: "{{ ip | ansible.utils.ipaddr }}"