- name: functions
  hosts: local
  connection: local
  vars:
    person: "ramesh,suresh,raheem,joseph"
  tasks: 
  - name: check undefined variable
    ansible.builtin.debug:
      msg: "hello {{ person | default('ramesh') }}"

  - name: print names
    ansible.builtin.debug:
       msg: "{{ person | split(',') }}"

