- name: play variables
  hosts: local
  connection: local
  vars:
  COURSE: Ansible
  DURATION: 10hr
  TRAINER: SUREKHA
  tasks:
  - name: print the course information
    ansible.builtin.debug:
      msg: "hello {{ COURSE }}, course duration {{ DURATION }}, trainer is {{ TRAINER }}"
  