- name: play level variables
  hosts: local
  connection: local
  tasks:
  - name: print course details
    vars:
      hello: ansible
      course: 10hrs for a day
      ansible.builtin.debug:
        msg: "{{ hello }},{{ course }}"